name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: affonso-rafael/test
          path: test

      - name: register key
        working-directory: test
        id: reg
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"
      
      - name: get key
        run: echo "sha is ${{steps.reg.outputs.sha}}"

      - name: Cache teste
        uses: actions/cache@v2
        env:
          cache-name: cache-perfil
        with:
          path: perfil
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ (git rev-parse HEAD) }}

    # - name: Check out repository
    #   uses: actions/checkout@v2

    # - name: Build
    #   run: |
    #     npm install
    #     npm run build

    # - name: Update repo with build
    #   uses: mikeal/publish-to-github-action@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     BRANCH_NAME: 'main'